### ISSUE TITLE
Difference between input and output midi port

### ISSUE THREAD

**Issue by ruiguo-bio** [PacktPublishing/hands-on-music-generation-with-magenta#12]
Hi Alexandre. In chapter 9, the port is opened by 
`def create_virtual_midi_ports():
    MidiHub(input_midi_ports=["magenta_in"],
          output_midi_ports=["magenta_out"],
          texture_type=None)`

I run that in a notebook. Then find midi_ports shows:

Input ports: ['magenta_out']
Output ports: ['FluidSynth virtual port (3570)', 'magenta_in']

Why the "magenta_in" is an output ports here, not "magenta_out"? If I send the note sequence to "magenta_out" by running the python files, it will open another ports called "magenta_out (port 2)", and that port will die after the program returns.

**Comment by dubreuia** [comment]
Hello @ruiguo-bio, thank you for opening an issue.

> If I send the note sequence to "magenta_out" by running the python files, it will open another ports called "magenta_out (port 2)", and that port will die after the program returns.

That means that the port you've provided isn't picked up by the MIDI library and it is opening a new virtual port `magenta_out (port 2)`. That virtual port is closed when the program exists like you said.

> Why the "magenta_in" is an output ports here, not "magenta_out"?

I've got the same thing, not exactly sure why they are reversed TBH:

```
Input ports: ['Midi Through:Midi Through Port-0 14:0', 'RtMidiOut Client:magenta_out 129:0']
Output ports: ['Midi Through:Midi Through Port-0 14:0', 'RtMidiIn Client:magenta_in 128:0']
```

But if you continue on in the example, it should work properly when you instantiate the `MidiHub` (we only need the output ports, because Magenta is only outputting MIDI, not receiving):

```
import mido
from magenta.interfaces.midi.midi_hub import MidiHub
# We find the proper input port for the software synth
# (which is the output port for Magenta)
output_ports = [name for name in mido.get_output_names()
if args.midi_port in name]
# Start a new MIDI hub on that port (output only)
midi_hub = MidiHub(input_midi_ports=[],
output_midi_ports=output_ports,
texture_type=None)
```

Let me know if it works out for you.

**Comment by ruiguo-bio** [comment]
Hi Alex. I think a better way is to set up midi port in OS X system as said in your book. The port set there will not be lost even if restart. Thanks for your help!
